name: CI
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

  # reusable
  workflow_call:

jobs:
  ci_trunk:
    if: github.event.pull_request.base.ref == 'trunk' || startsWith(github.event.pull_request.base.ref, 'rebase_dev_trunk')
    uses: open-vela/public-actions/.github/workflows/ci.yml@trunk
    secrets: inherit

  ci_dev:
    if: github.event.pull_request.base.ref == 'dev'
    uses: open-vela/public-actions/.github/workflows/ci-real.yml@dev
    secrets: inherit
