name: docs

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

  # reusable
  workflow_call:

jobs:
  docs:
    # Only run on PR events
    if: github.event_name == 'pull_request_target' || github.event_name == 'workflow_call'
    uses: open-vela/public-actions/.github/workflows/docs-real.yml@trunk
    secrets: inherit
