name: docs

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

  # reusable
  workflow_call:

jobs:
  cla:
    # Run on PR events or /check-cla comment
    if: github.event_name == 'pull_request_target' || github.event_name == 'workflow_call' || (github.event.issue.pull_request && contains(github.event.comment.body, '/check-cla'))
    uses: open-vela/public-actions/.github/workflows/cla.yml@dev
    secrets: inherit

  docs:
    # Only run on PR events, not on comments
    if: github.event_name == 'pull_request_target' || github.event_name == 'workflow_call'
    uses: open-vela/public-actions/.github/workflows/docs-real.yml@dev
    secrets: inherit
